%% Explanation of FSFG hydrogel FRAP experiments and Fourier series analysis

% This is a set of instructions for processing and analyzing FRAP
% experiments on FSFG hydrogels as run by Laura and described in lab
% notebook 6.  The overall workflow is: enter experiment information and
% create a folder for an individual experiment; process an individual
% experiment; combine processed experiments into a dataset and define
% masks; fit the results to a Fourier series and extract a value for
% diffusion constant D.

% STEP 1: Run expInfoFRAP.m
% Fill in the relevant information and run the file for every segment of
% the FRAP experiment except the pre-bleach snapshot.  This script creates
% a dated "info" structure and saves it in a dated subfolder in the
% Processed Images folder on the Z-drive.  Most of the experiments I ran
% had two segments and therefore generated two folders (e.g. "2019-2-15_1"
% and "2019-2-15_2").  In order to keep track of which experiment segments
% go together, use the fields for extra notes.  Running expInfoFRAP.m twice
% with the same date and index rewrites the data in the experiment folder.

% STEP 2: Run FRAP_processing_190513.m
% All of the input information is in the first section.  Provide full file
% paths to the 'info' structure for both segments of the experiment (i.e.
% these file paths should point to the experiment folders and 'info'
% structure created in step 1, NOT to the raw microscopy data files).  In
% contrast, the file path for the pre-bleach snapshot should point to the
% raw microscopy file. Input offsets, frame numbers, and frame timing as
% well (these should be noted somewhere in the 'info' structure as well.)
% You should be able to run the script straight through after filling in
% the first section, assuming that a pre-bleach snapshot exists and there
% are two recovery segments.  If not, some fiddling will be required but
% hopefully just commenting and un-commenting some lines.

% This script combines the pre-bleach snapshot and the two recovery
% segments into one series of images and creates an appropriate time axis
% (in seconds).  It makes an avi movie file of the experiment (with all
% frames equally spaced, regardless of the time axis) with automatic
% scaling in the red and green channels.  The movie is saved in the
% experiment folder corresponding to the first segment of the experiment.
% A 'results' structure is saved in the same folder with some basic
% information about the experiment and the complete time series of images
% (making this structure large and time-consuming to load).

% STEP 3: Run FRAP_dataset_190513.m
% This script combines many individual experiments and creates the
% information necessary for a Fourier series fit.  I've kept the folder
% names and parameters used for the dataset in my thesis (only entries 1:43
% are actually used in the dataset and some errors might happen if numbers
% 44:51 are run, but I didn't want to change anything).  Users need to
% input a list of experiment folders (i.e. those generated by expInfoFRAP)
% and a corresponding list of gel types and concentrations.

% This script first imports the 'results' structure from the experiment
% folder, which takes up to a minute.  The user then must define the masks
% that will be used during the analysis.  First, draw a mask which
% encompasses the entire gel, minus the non-equilibrated portion of the
% edge.  The perimeter of this gel is fixed at the equilibrium
% concentration by the analysis, so don't include the non-equilibrated edge
% region.  Bright/dark spots can be avoided to a degree, but keep in mind
% that the widest row of this mask is used to set the diameter and center
% location of the gel.  Second, draw a mask which covers the bleach spot
% only.  BE VERY CAREFUL if the gel develops a weird ring towards the end
% of the experiment (look at every avi file before running this to check).
% The ring must not be included in the bleach spot mask, but some fiddling
% with the code will need to be done so that the final green image is
% displayed and the ring is visible in the image used to define the mask.
% The bleach spot mask can also be drawn to avoid weird bright/dark spots.
% Third, draw a mask which covers the reservoir, avoiding weird bright/dark
% spots.  This mask is used when calculating partition coefficients but as
% long as you get a good, fairly large portion of the reservoir, the size
% and shape don't really matter.  Finally, draw a mask which covers only
% the equilibrated portions of the hydrogel.  This mask is also used when
% calculating partition coefficient, as well as to calculated the
% equilibrated concentration of the gel.

% After asking for the masks, the script calculates the normalized recovery
% curves seen in the experiment, as well as the partition coefficients and
% bound probability.  These results are saved in the 'data' structure in
% the workspace ONLY.  Remember to save this structure somewhere else
% before closing.

% STEP 4: Run runAllNumerical_190513
% This script takes no inputs.  Make sure the 'data' structure generated in
% step 3 is in the workspace.  This script takes a long time to run (about
% 24 hours for a set of 43 experiments, Nterms = 20, on a desktop
% computer).  This script creates the Fourier series solution to the
% diffusion equation as described in Laura's thesis chapter 4 and in the
% Carslaw book.  First, the coefficients for each mode are calculated and
% stored in arrays.  Second, the initial post-bleach image is reconstructed
% (this step isn't necessary for the fit, but it's a good check that the
% coefficients are good).  Next, the fit string is computed.  This is a
% string that will be fed into Matlab's curve fitter to extract a value for
% D.  It's really long (400 terms if Nterms = 20) and contains only D as a
% free parameter.  It describes the average bleach spot intensity
% normalized to the overall gel intensity.  It is not yet properly
% normalized to the data.  The next step is to generate string 'K', which
% contains two additional parameters that control the bleach depth and
% final aysmptotic recovered value.  Lastly, the fit is performed.

% All results are saved ONLY to the 'data' structure in the workspace, so
% BE SURE TO SAVE THIS STRUCTURE.  For long runs, it's a good idea to add a
% line which saves the workspace between each experiment.

% The proper way to normalize the series solution is not trivial and is
% best described by looking at the code itself.